// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS5462AA5_Ifzb9k1VQJFCM12xvgD58zU',
    appId: '1:78126192929:web:b196288357f67565db8660',
    messagingSenderId: '78126192929',
    projectId: 'reddit-clone-aec34',
    authDomain: 'reddit-clone-aec34.firebaseapp.com',
    storageBucket: 'reddit-clone-aec34.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv6fN4IWDZe561X7pD3N6nFLHhSnHcSJc',
    appId: '1:78126192929:android:0201ec690f79df3cdb8660',
    messagingSenderId: '78126192929',
    projectId: 'reddit-clone-aec34',
    storageBucket: 'reddit-clone-aec34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeK2j75peAK5w7IHU32SIPGyZakHRZ3hk',
    appId: '1:78126192929:ios:eb2c3bae30914a7fdb8660',
    messagingSenderId: '78126192929',
    projectId: 'reddit-clone-aec34',
    storageBucket: 'reddit-clone-aec34.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );
}
